from __future__ import annotations

import re

from app.prompting.builder import NO_CONTEXT_MESSAGE
from app.providers.base import ProviderResponse, estimate_tokens

MOCK_PROVIDER_NOTE = (
    "Note: this response was generated by the deterministic mock provider. "
    "Real LLM generation is not implemented yet."
)
NO_CONTEXT_RESPONSE = (
    "I could not find relevant documentation context for this question in the "
    "current local corpus, so I should not fabricate a source-grounded answer."
)
CONTEXT_RESPONSE_INTRO = (
    "Based on the retrieved documentation context, I would start with these checks:"
)


class MockLLMProvider:
    model = "mock"

    def generate(self, prompt: str) -> ProviderResponse:
        input_tokens = estimate_tokens(prompt)
        text = _build_mock_response(prompt)
        output_tokens = estimate_tokens(text)

        return ProviderResponse(
            text=text,
            model=self.model,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=input_tokens + output_tokens,
        )


def _build_mock_response(prompt: str) -> str:
    if NO_CONTEXT_MESSAGE in prompt:
        return f"{NO_CONTEXT_RESPONSE}\n\n{MOCK_PROVIDER_NOTE}"

    sources = _parse_source_labels(prompt)
    source_lines = "\n".join(f"- {source}" for source in sources)

    return "\n".join(
        [
            CONTEXT_RESPONSE_INTRO,
            "",
            "1. Review the documented diagnostic signals in the retrieved context.",
            "2. Check scheduling, workload, or configuration constraints mentioned "
            "in the retrieved context.",
            "3. Prefer safe diagnostic checks before making destructive changes.",
            "",
            "Sources used:",
            source_lines,
            "",
            MOCK_PROVIDER_NOTE,
        ]
    )


def _parse_source_labels(prompt: str) -> list[str]:
    labels: list[str] = []
    current_title: str | None = None

    for line in prompt.splitlines():
        if match := re.match(r"^title:\s*(.+)$", line):
            current_title = match.group(1).strip()
            continue

        if match := re.match(r"^heading:\s*(.+)$", line):
            heading = match.group(1).strip()
            label = _source_label(current_title, heading)
            if label not in labels:
                labels.append(label)
            current_title = None

    if labels:
        return labels
    return ["Retrieved documentation context"]


def _source_label(title: str | None, heading: str) -> str:
    if title and heading and heading != "null" and heading != title:
        return f"{title} - {heading}"
    if title:
        return title
    if heading and heading != "null":
        return heading
    return "Retrieved documentation context"
